# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: aomaのページ
email:
description: >- # this means to ignore newlines until "baseurl:"
  aomaです。
twitter_username: aoma23
github_username: aoma23
minimal_mistakes_skin: air
search: true
url: https://aoma23.com
lang: ja
locale: ja_JP
og_image: "/assets/images/aoma-og-1200x630.png"
twitter:
  username: naoqoo2

# Build settings
markdown: kramdown
repository: "mmistakes/minimal-mistakes"
remote_theme: mmistakes/minimal-mistakes
# Outputting
# permalink: /:categories/:title/
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Tokyo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
date_format: "%Y-%m-%d"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "aoma"
  avatar : "/assets/images/aoma.png"
  bio    : "aomaです。エンジニアしてます。"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://aoma23.com/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/aoma23"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  # links:
  #   - label: "Twitter"
  #     icon: "fab fa-fw fa-twitter-square"
  #     url: "https://twitter.com/"
  #   - label: "GitHub"
  #     icon: "fab fa-fw fa-github"
  #     url: "https://github.com/"
  #   - label: "Instagram"
  #     icon: "fab fa-fw fa-instagram"
  #     url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      classes: wide #記事の表示幅を広げる
      image: "/assets/images/aoma-og-1200x630.png"
      og_image: "/assets/images/aoma-og-1200x630.png"

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      image: "/assets/images/aoma-og-1200x630.png"
      og_image: "/assets/images/aoma-og-1200x630.png"

# category_archive:
#   type: liquid
#   path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "GTM-MF9338WT"
    anonymize_ip: false # default

head_scripts:
  - /assets/js/ad.js
